<template>
  <div>
    <div class="backwrap gradient">
    <div class="back-shapes">
        <!-- All this img tags was autogenerated by custom written js tool -->
        <span class="floating circle" style="top:66.59856996935649%;left:13.020833333333334%;animation-delay:-0.9s;"></span>
        <span class="floating triangle" style="top:31.46067415730337%;left:33.59375%;animation-delay:-4.8s;"></span>
        <span class="floating cross" style="top:76.50663942798774%;left:38.020833333333336%;animation-delay:-4s;"></span>
        <span class="floating square" style="top:21.450459652706844%;left:14.0625%;animation-delay:-2.8s;"></span>
        <!-- <span class="floating square" style="top:58.12053115423902%;left:56.770833333333336%;animation-delay:-2.15s;"></span> -->
        <span class="floating square" style="top:8.682328907048008%;left:72.70833333333333%;animation-delay:-1.9s;"></span>
        <span class="floating cross" style="top:31.3585291113381%;left:58.541666666666664%;animation-delay:-0.65s;"></span>
        <span class="floating cross" style="top:69.96935648621042%;left:81.45833333333333%;animation-delay:-0.4s;"></span>
        <!-- <span class="floating circle" style="top:15.117466802860061%;left:32.34375%;animation-delay:-4.1s;"></span> -->
        <!-- <span class="floating circle" style="top:13.074565883554648%;left:45.989583333333336%;animation-delay:-3.65s;"></span> -->
        <span class="floating cross" style="top:55.87334014300306%;left:27.135416666666668%;animation-delay:-2.25s;"></span>
        <!-- <span class="floating cross" style="top:49.54034729315628%;left:53.75%;animation-delay:-2s;"></span> -->
        <!-- <span class="floating cross" style="top:34.62717058222676%;left:49.635416666666664%;animation-delay:-1.55s;"></span> -->
        <span class="floating cross" style="top:33.19713993871297%;left:86.14583333333333%;animation-delay:-0.95s;"></span>
        <!-- <span class="floating square" style="top:28.19203268641471%;left:25.208333333333332%;animation-delay:-4.45s;"></span> -->
        <!-- <span class="floating circle" style="top:39.7344228804903%;left:10.833333333333334%;animation-delay:-3.35s;"></span> -->
        <span class="floating triangle" style="top:77.83452502553627%;left:24.427083333333332%;animation-delay:-2.3s;"></span>
        <!-- <span class="floating triangle" style="top:2.860061287027579%;left:47.864583333333336%;animation-delay:-1.75s;"></span> -->
        <span class="floating triangle" style="top:71.3993871297242%;left:66.45833333333333%;animation-delay:-1.25s;"></span>
        <span class="floating triangle" style="top:31.256384065372828%;left:76.92708333333333%;animation-delay:-0.65s;"></span>
        <span class="floating triangle" style="top:46.47599591419816%;left:38.90625%;animation-delay:-0.35s;"></span>
        <span class="floating cross" style="top:3.4729315628192032%;left:19.635416666666668%;animation-delay:-4.3s;"></span>
        <span class="floating cross" style="top:3.575076608784474%;left:6.25%;animation-delay:-4.05s;"></span>
        <span class="floating cross" style="top:77.3237997957099%;left:4.583333333333333%;animation-delay:-3.75s;"></span>
        <span class="floating cross" style="top:0.9193054136874361%;left:71.14583333333333%;animation-delay:-3.3s;"></span>
        <!-- <span class="floating square" style="top:23.6976506639428%;left:63.28125%;animation-delay:-2.1s;"></span> -->
        <!-- <span class="floating square" style="top:81.30745658835546%;left:45.15625%;animation-delay:-1.75s;"></span> -->
        <!-- <span class="floating square" style="top:60.9805924412666%;left:42.239583333333336%;animation-delay:-1.45s;"></span> -->
        <span class="floating square" style="top:29.009193054136876%;left:93.90625%;animation-delay:-1.05s;"></span>
        <!-- <span class="floating square" style="top:52.093973442288046%;left:68.90625%;animation-delay:-0.7s;"></span> -->
        <span class="floating square" style="top:81.51174668028601%;left:83.59375%;animation-delay:-0.35s;"></span>
        <span class="floating square" style="top:11.542390194075587%;left:91.51041666666667%;animation-delay:-0.1s;"></span>
      </div>
    </div>
    <Header
      v-bind:headOnColor="headOnColor"
      v-bind:headOffColor="headOffColor"
      v-bind:btnOnColor="btnOnColor"
      v-bind:btnOffColor="btnOffColor" 
    />
    <div class="mainCon">
      <div class="left" >
        <span class="f1">We've</span>
        <span class="f2">had</span>
        <span class="f3">a</span>
        <span class="f4" id="dark">TEDx</span>
        <span class="f5">day.</span>
      </div>
    </div>


    <div class="py-10 black" style="text-align: center">
    
      <div>
        <div colum xs10>
          <h1 class="mb-3" style="color: white; margin-top: 5vw;">About   <span class="RT"> TEDx</span></h1>
            <myLine :height="30"/>
          <v-flex class="aboutText"> 
            <div style="color: black; margin: auto; width: 70vw;  margin-bottom: 3vw; margin-top: 10vw ">{{AboutText_ko1}}</div>
            <div style="color: black; margin: auto; width: 70vw;  margin-bottom: 15vw">{{AboutText_en1}}</div>
          </v-flex>
        </div>
        
        <div colum xs10>          
          <h1 class="mb-3"  style="color: white; margin-top: 12vw;">About <span class="RT">TEDx </span>Hanyang U</h1>          
            <myLine :height="30"/>
          <v-flex class="aboutText">  
            <div style="color: black; margin: auto; width: 70vw; margin-bottom: 3vw; margin-top:10vw ">{{AboutText_ko2}}</div>
            <div style="color: black; margin: auto; width: 70vw; margin-bottom: 15vw">{{AboutText_en2}}</div>
          </v-flex>
        </div>

        <div colum xs10>
          <h1 class="mb-3" style="color: white; margin-top:12vw;">Connect <span class="type"><span class="RT">TEDx </span>Hanyang U</span></h1>
            <myLine :height="30"/>
          <v-flex class="aboutText_3" style= "height: 60vw;">
            <div style="color: black; margin: auto; width: 70vw; margin-bottom: 3vw; margin-top: 10vw">{{AboutText_ko3}}</div>
            <div style="color: black; margin: auto; width: 70vw">{{AboutText_en3}}</div>
            
            <div class="grid">
                <div class="grid__item">
                    <div class="card"><img class="card__img" src="https://images.unsplash.com/photo-1567443024551-f3e3cc2be870?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="youtube_img">
                        <div class="card__content">
                            <h1 class="card__header" style="font-family: Roboto-Black; font-size: 35px">You Tube</h1>
                            <p class="card__text"> </p><button class="card__btn" type="button" a herf="#" onclick="window.open('https://www.youtube.com/results?search_query=tedxhanyangu','youtube'); return false">Go youtube <span>&rarr;</span></button></div>
                    </div>
                </div>
                <div class="grid__item">
                    <div class="card"><img class="card__img" src="https://images.unsplash.com/photo-1505322747495-6afdd3b70760?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="insta_img">
                        <div class="card__content">
                            <h1 class="card__header" style="font-family: billabong; font-size: 35px">Instagram</h1>
                            <p class="card__text"></p><button class="card__btn" type="button" a herf="#" onclick="window.open('https://www.instagram.com/tedxhanyangu_2020/','instagram'); return false" >Go instagram <span>&rarr;</span></button></div>
                    </div>
                </div>
                <div class="grid__item">
                    <div class="card"><img class="card__img" src="https://images.unsplash.com/photo-1517292987719-0369a794ec0f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1934&q=80" alt="facebook_img">
                        <div class="card__content">
                            <h1 class="card__header" style="font-family: FACEBOLF; font-size: 35px">face book</h1>
                            <p class="card__text"></p><button class="card__btn" type="button" a herf="#" onclick="window.open('https://www.facebook.com/TEDxHanyangU/','facebook'); return false">Go facebook <span>&rarr;</span></button></div>
                    </div>
                </div>
            </div>
          </v-flex>
        </div>
      </div>
    </div>
  
  </div>
</template>

<script>
/*import { VueTyper } from 'vue-typer'*/
import {AboutText_ko1, AboutText_en1,AboutText_ko2, AboutText_en2,AboutText_ko3, AboutText_en3} from '@/constant.js'
import myLine from '@components/About/Line'
export default {
  name: "About",
  data() {
    return {
      AboutText_ko1, AboutText_en1,
      AboutText_ko2, AboutText_en2,
      AboutText_ko3, AboutText_en3,
      headOnColor: "rgba(255, 255, 255, 1)",
      headOffColor: "rgba(255, 255, 255, 0)",
      btnOnColor: "black",
      btnOffColor: "white"
    }
  },
  components: {
    myLine: myLine,
    /*VueTyper: VueTyper*/
  }
};
</script>
<style>
@import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Gothic+A1:wght@200;300&display=swap');
.backwrap {
  background:rgba(0, 0, 0, 0.0);
  background-repeat: no-repeat;
  background-size: 100% 100%;
  width: 100%;
  height: 100%;
  position: fixed;
  left: 0;
  top: 0;
  z-index: 1;
  
}

/* Shapes & Animation
*/
.back-shapes {
  width: 100%;
  height: 100%;
  position: relative;
  overflow: hidden;
}

.back-shapes img {
  opacity: 0.2;
  position: absolute;
  width: 1.5%;
}

.floating {
  position: absolute;
  animation-name: floating;
  -webkit-animation-name: floating;
  animation-duration: 5s;
  -webkit-animation-duration: 5s;
  animation-iteration-count: infinite;
  -webkit-animation-iteration-count: infinite;
}

.floating.square {
  display: inline-block;
  width: 35px;
  height: 35px;
  background-image: url("../assets/image/square.jpg");
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center center;
  opacity: 0.5;
}
.floating.triangle {
  display: inline-block;
  width: 35px;
  height: 35px;
  background-image: url("../assets/image/triangle.jpg");
  background-repeat: no-repeat;
  background-position: center center;
  opacity: 0.5;
}
.floating.cross {
  display: inline-block;
  width: 35px;
  height: 35px;
  background-image: url("../assets/image/cross.jpg");
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center center;
  opacity: 0.5;
}

@keyframes floating {
  0% {
    transform: translateY(0%) rotate(-55deg);
  }
  50% {
    transform: translateY(300%) rotate(55deg);
  }
  100% {
    transform: translateY(0%) rotate(-55deg);
  }
}
@-webkit-keyframes floating {
  0% {
    -webkit-transform: translateY(0%);
  }
  50% {
    -webkit-transform: translateY(300%);
  }
  100% {
    -webkit-transform: translateY(0%);
  }
}

Header{
  background-color: black;
}
section {
  background-color: black;
  height: 1000px;  
}
.RT{
  color: red;
  
}
.mb-3 {
  font-family: 'Permanent Marker', cursive;
  font-size: 50px;
}

.aboutText{
  display: flex;
  flex-direction: column;
  background-color: white;
  border-bottom-left-radius: 5vw;
  border-bottom-right-radius: 5vw;
  box-shadow: 5px 5px 5px 5px gray;
  height: 40vw;
  font-size: larger;
  font-family: 'Gothic A1', sans-serif;
}

.aboutText_3{
  display: flex;
  flex-direction: column;
  background-color: white;
  box-shadow: 5px 5px 5px 5px gray;
  height: 40vw;
  font-size: larger;
  font-family: 'Gothic A1', sans-serif;
}




@media screen and (max-width: 1196px){
  .aboutText {
    height: auto;
  }
}

@media screen and (max-width: 707px){
  .aboutText_3 {
  height: 80vw;
  }
  
}

/* */
@import url('https://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700');
@import url('https://fonts.googleapis.com/css?family=Raleway:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i');

*,
*::before,
*::after {
  margin: 0;
  padding: 0;
  box-sizing: inherit;
}




.grid {
  
  justify-content: center;
  align-content: center;
  padding: 6rem;
  background-color: white;
  font-family: 'Gothic A1', sans-serif;
  box-sizing: border-box;
  display: grid;
  grid-template-columns: 2fr 2fr 2fr;
  width: 100%;
  grid-gap: 6rem;
  grid-auto-rows: auto;
  align-items: start;
}

.grid__item {
  z-index: 100;
  background-color: #fff;
  border-radius: 0.4rem;
  overflow: hidden;
  box-shadow: 0 3rem 6rem rgba(0, 0, 0, 0.1);
  cursor: pointer;
  transition: 0.2s;

  
}
.grid__item:hover {
  transform: translateY(-0.5%);
  box-shadow: 0 4rem 8rem rgba(0, 0, 0, 0.2);
}

.card__img {
  display: block;
  width: 100%;
  height: 15rem;
  object-fit: cover;
}
.card__content {
  padding: 1rem 1rem;

}
.card__header {
  font-size: 1.5rem;
  font-weight: 500;
  color: #0d0d0d;
  margin-bottom: 1.5rem;
  
}
.card__text {
  font-size: 1.rem;
  letter-spacing: 0.1rem;
  line-height: 1.7;
  color: #3d3d3d;
  margin-bottom: 2.5rem;
}
.card__btn {
  display: block;
  width: 100%;
  padding: 1.5rem;
  font-size: 1.5rem;
  text-align: center;
  color: white;
  background-color: #ff9999;
  border: none;
  border-radius: 0.4rem;
  transition: 0.2s;
  cursor: pointer;
}
.card__btn span {
  margin-left: 1rem;
  transition: 0.2s;
}
.card__btn:hover, .card__btn:active {
  background-color: #ff6666;
}
.card__btn:hover span, .card__btn:active span {
  margin-left: 1.5rem;
}


@media screen and (max-width: 890px){
.grid {
  display: flex;
  flex-direction: column;
  
}
}

@media screen and (max-width: 500px){
.grid__item {
  font-size: 0.7rem;
}

}

@import url('https://fonts.googleapis.com/css?family=Shadows+Into+Light');
@import url('https://fonts.googleapis.com/css?family=Amatic+SC');


.mainCon{
  height:90vh;
  overflow: hidden;
  display: block;
  position: relative;
  padding-bottom: 150px;
  background:#d3d0cb;
  margin:0;
  animation: back .1s linear;
  animation-fill-mode:forwards;
  animation-delay:1.5s;
  overflow:hidden;
  
  


}
@keyframes back{
  0% {
    background-color:#d3d0cb;
  }
  100% {
    background-color: black;
  }
}

.left{
  display:flex;
  width:30%;
  height:600px;
  margin:auto;
  flex-direction:column;
  margin-left:40%;
  margin-top:4%;

}

.f1,.f2,.f3,.f4,.f5 {
  /* font-family: 'Shadows Into Light', cursive; */
  font-family: 'tvNE';
  line-height:1;
  font-size:110px;
  position:absolute;
}

#dark{
  /* font-family: 'Amatic SC', cursive; */
  font-family: 'tvNE'
}

.f1{
  
  margin-top:-7em;
  animation: weve, text;
  animation-duration:.8s, .3s;
  animation-delay: 0s, 1.5s;
  animation-fill-mode:forwards;
}

@keyframes weve{
  from{margin-top:-7em}
  to{margin-top:0}
}

.f2{
  margin-top:-7em;
  margin-left:.5em;
  animation: had, text;
  animation-duration:.8s, .3s;
  animation-delay:.5s, 1.5s;
  animation-fill-mode:forwards;
}

@keyframes had{
  from{margin-top:-7em;}
  to{margin-top:.7em;}
}

.f3{
  margin-left:.3em;
  margin-top:-7em;
  animation: some, text;
  animation-duration:.8s, .3s;
  animation-delay:.8s, 1.5s;
  animation-fill-mode:forwards;
  align-content: center;
  text-align: center
}

@keyframes some{
  from{margin-top:-7em;}
  to{margin-top:1.3em;}
}

.f4{
  margin-top:1.5em;
  margin-left:.1em;
  animation:dark .2s linear;
  animation-fill-mode:forwards;
  font-size:150px;
  opacity:0;
  animation-delay:1.5s;
  color:RED;
  
}

@keyframes dark{
  from{opacity:0}
  to{opacity:1}
}


.f5{
  margin-top:3.5em;
  animation: days .5s linear;
  animation-fill-mode:forwards;
  font-size:110px;
  margin-left:.4em;
  animation-delay:1.8s;
  color:#d3d0cb;
  opacity:0;
}

@keyframes days{
  from{opacity:0;
  }
  to{opacity:1;}
}

@keyframes text{
  from{color:black}
  to{color:#d3d0cb}
}

/*.mainCon{*/
 /* height:90vh;
  overflow: hidden;
  display: block;
  position: relative;
  padding-bottom: 150px;
}*/

@media screen and (max-width:600px){
  .left{
    margin-left:30%;
  }
}

@media screen and (max-width:450px){
  .left{
    margin-left:20%;
  }
}

@media screen and (max-height:1400px){
  .footer{
    display:none;
  }
}



</style>
